/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinematicaparticula;

import java.awt.Color;

/**
 *
 * @author renzo
 */
public class CinematicaP extends javax.swing.JFrame {

    /**
     * Creates new form CinematicaP
     */
    public CinematicaP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPasswordField1 = new javax.swing.JPasswordField();
        background = new javax.swing.JPanel();
        background_title = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Separator1 = new javax.swing.JSeparator();
        ground5 = new javax.swing.JPanel();
        Value5 = new javax.swing.JLabel();
        imput_value5 = new javax.swing.JTextField();
        ground6 = new javax.swing.JPanel();
        Value6 = new javax.swing.JLabel();
        imput_value6 = new javax.swing.JTextField();
        Separator_General5 = new javax.swing.JSeparator();
        Ground_Derivada = new javax.swing.JPanel();
        Derivada = new javax.swing.JLabel();
        Position = new javax.swing.JLabel();
        Value_position = new javax.swing.JTextField();
        Speed = new javax.swing.JLabel();
        Value_speed = new javax.swing.JTextField();
        acceleration = new javax.swing.JLabel();
        Value_acceleration = new javax.swing.JTextField();
        Calculator1 = new javax.swing.JButton();
        Ground_fun_time = new javax.swing.JPanel();
        fun_time_titile = new javax.swing.JLabel();
        fun_position = new javax.swing.JLabel();
        result_position = new javax.swing.JTextField();
        fun_speed = new javax.swing.JLabel();
        result_speed = new javax.swing.JTextField();
        fun_aceleration = new javax.swing.JLabel();
        result_aceleration = new javax.swing.JTextField();
        Calculator = new javax.swing.JButton();
        Separator2 = new javax.swing.JSeparator();
        Calculator2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Boton_de_inicio = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 102));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background_title.setBackground(new java.awt.Color(255, 204, 204));
        background_title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        background_title.setForeground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Title.setText("CÁLCULO CON DERIVADAS");

        javax.swing.GroupLayout background_titleLayout = new javax.swing.GroupLayout(background_title);
        background_title.setLayout(background_titleLayout);
        background_titleLayout.setHorizontalGroup(
            background_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        background_titleLayout.setVerticalGroup(
            background_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        background.add(background_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 360, 60));

        Separator1.setForeground(new java.awt.Color(0, 153, 153));
        Separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        background.add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 20, 300));

        ground5.setBackground(new java.awt.Color(0, 153, 153));
        ground5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        ground5.setForeground(new java.awt.Color(0, 51, 102));
        ground5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ground5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ground5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ground5MouseExited(evt);
            }
        });

        Value5.setBackground(new java.awt.Color(0, 204, 0));
        Value5.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        Value5.setForeground(new java.awt.Color(204, 255, 204));
        Value5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Value5.setText("TIEMPO");

        imput_value5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        imput_value5.setForeground(new java.awt.Color(204, 204, 204));
        imput_value5.setText("T");
        imput_value5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imput_value5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imput_value5MousePressed(evt);
            }
        });
        imput_value5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imput_value5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ground5Layout = new javax.swing.GroupLayout(ground5);
        ground5.setLayout(ground5Layout);
        ground5Layout.setHorizontalGroup(
            ground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Value5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ground5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(imput_value5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        ground5Layout.setVerticalGroup(
            ground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ground5Layout.createSequentialGroup()
                .addComponent(Value5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imput_value5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        background.add(ground5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, 80));

        ground6.setBackground(new java.awt.Color(153, 153, 0));
        ground6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ground6.setForeground(new java.awt.Color(153, 153, 0));
        ground6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ground6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ground6MouseExited(evt);
            }
        });

        Value6.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        Value6.setForeground(new java.awt.Color(204, 255, 102));
        Value6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Value6.setText("DISTANCIA");

        imput_value6.setEditable(false);
        imput_value6.setBackground(new java.awt.Color(255, 255, 255));
        imput_value6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        imput_value6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imput_value6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ground6Layout = new javax.swing.GroupLayout(ground6);
        ground6.setLayout(ground6Layout);
        ground6Layout.setHorizontalGroup(
            ground6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Value6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ground6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imput_value6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        ground6Layout.setVerticalGroup(
            ground6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ground6Layout.createSequentialGroup()
                .addComponent(Value6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imput_value6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        background.add(ground6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 160, 80));

        Separator_General5.setBackground(new java.awt.Color(153, 0, 0));
        Separator_General5.setForeground(new java.awt.Color(0, 153, 153));
        Separator_General5.setDoubleBuffered(true);
        Separator_General5.setFocusCycleRoot(true);
        background.add(Separator_General5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 510, 20));

        Ground_Derivada.setBackground(new java.awt.Color(153, 102, 0));
        Ground_Derivada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Derivada.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        Derivada.setForeground(new java.awt.Color(153, 153, 255));
        Derivada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Derivada.setText("DERIVADAS");

        Position.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        Position.setForeground(new java.awt.Color(255, 204, 255));
        Position.setText("Posición:");

        Value_position.setEditable(false);
        Value_position.setBackground(new java.awt.Color(255, 255, 255));
        Value_position.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Value_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Value_positionActionPerformed(evt);
            }
        });

        Speed.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        Speed.setForeground(new java.awt.Color(255, 204, 204));
        Speed.setText("Velocidad:");

        Value_speed.setEditable(false);
        Value_speed.setBackground(new java.awt.Color(255, 255, 255));
        Value_speed.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        acceleration.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        acceleration.setForeground(new java.awt.Color(204, 204, 255));
        acceleration.setText("Aceleración:");

        Value_acceleration.setEditable(false);
        Value_acceleration.setBackground(new java.awt.Color(255, 255, 255));
        Value_acceleration.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        Calculator1.setBackground(new java.awt.Color(153, 0, 0));
        Calculator1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        Calculator1.setForeground(new java.awt.Color(255, 255, 255));
        Calculator1.setText("MOSTRAR");
        Calculator1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculator1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Calculator1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Calculator1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Calculator1MouseExited(evt);
            }
        });
        Calculator1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculator1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Ground_DerivadaLayout = new javax.swing.GroupLayout(Ground_Derivada);
        Ground_Derivada.setLayout(Ground_DerivadaLayout);
        Ground_DerivadaLayout.setHorizontalGroup(
            Ground_DerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ground_DerivadaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Ground_DerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Value_position)
                    .addComponent(Value_speed)
                    .addComponent(Value_acceleration)
                    .addGroup(Ground_DerivadaLayout.createSequentialGroup()
                        .addGroup(Ground_DerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Speed, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acceleration, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
            .addComponent(Derivada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Ground_DerivadaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Calculator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        Ground_DerivadaLayout.setVerticalGroup(
            Ground_DerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ground_DerivadaLayout.createSequentialGroup()
                .addComponent(Derivada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Position)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Value_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Speed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Value_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acceleration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Value_acceleration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Calculator1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        background.add(Ground_Derivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 270, 300));

        Ground_fun_time.setBackground(new java.awt.Color(102, 153, 0));
        Ground_fun_time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        fun_time_titile.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        fun_time_titile.setForeground(new java.awt.Color(153, 255, 153));
        fun_time_titile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fun_time_titile.setText("FUNCION DEL TIEMPO");
        fun_time_titile.setFocusable(false);
        fun_time_titile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fun_time_titile.setVerifyInputWhenFocusTarget(false);

        fun_position.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        fun_position.setForeground(new java.awt.Color(255, 204, 255));
        fun_position.setText("Posicion:");

        result_position.setEditable(false);
        result_position.setBackground(new java.awt.Color(255, 255, 255));
        result_position.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        result_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_positionActionPerformed(evt);
            }
        });

        fun_speed.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        fun_speed.setForeground(new java.awt.Color(255, 204, 204));
        fun_speed.setText("Velocidad:");

        result_speed.setEditable(false);
        result_speed.setBackground(new java.awt.Color(255, 255, 255));
        result_speed.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        result_speed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_speedActionPerformed(evt);
            }
        });

        fun_aceleration.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        fun_aceleration.setForeground(new java.awt.Color(204, 204, 255));
        fun_aceleration.setText("Aceleracion:");

        result_aceleration.setEditable(false);
        result_aceleration.setBackground(new java.awt.Color(255, 255, 255));
        result_aceleration.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout Ground_fun_timeLayout = new javax.swing.GroupLayout(Ground_fun_time);
        Ground_fun_time.setLayout(Ground_fun_timeLayout);
        Ground_fun_timeLayout.setHorizontalGroup(
            Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ground_fun_timeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fun_position, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fun_speed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(fun_aceleration, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(result_speed)
                    .addComponent(result_position)
                    .addComponent(result_aceleration, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(fun_time_titile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Ground_fun_timeLayout.setVerticalGroup(
            Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ground_fun_timeLayout.createSequentialGroup()
                .addComponent(fun_time_titile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fun_position))
                .addGap(18, 18, 18)
                .addGroup(Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fun_speed))
                .addGap(18, 18, 18)
                .addGroup(Ground_fun_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fun_aceleration)
                    .addComponent(result_aceleration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        background.add(Ground_fun_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 250, 180));

        Calculator.setBackground(new java.awt.Color(153, 0, 0));
        Calculator.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        Calculator.setForeground(new java.awt.Color(255, 255, 255));
        Calculator.setText("CALCULAR");
        Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CalculatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CalculatorMouseExited(evt);
            }
        });
        Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorActionPerformed(evt);
            }
        });
        background.add(Calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 120, 40));

        Separator2.setForeground(new java.awt.Color(0, 153, 153));
        Separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        background.add(Separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 20, 300));

        Calculator2.setBackground(new java.awt.Color(153, 0, 0));
        Calculator2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        Calculator2.setForeground(new java.awt.Color(255, 255, 255));
        Calculator2.setText("CALCULAR");
        Calculator2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculator2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Calculator2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Calculator2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Calculator2MouseExited(evt);
            }
        });
        Calculator2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculator2ActionPerformed(evt);
            }
        });
        background.add(Calculator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 120, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinematicaparticula/Imagen/UA_logo_de_la_universidad_autónoma (1) (1).png"))); // NOI18N
        background.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        Boton_de_inicio.setBackground(new java.awt.Color(204, 102, 0));
        Boton_de_inicio.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        Boton_de_inicio.setForeground(new java.awt.Color(255, 255, 0));
        Boton_de_inicio.setText("INICIO");
        Boton_de_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_de_inicioMouseClicked(evt);
            }
        });
        Boton_de_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_de_inicioActionPerformed(evt);
            }
        });
        background.add(Boton_de_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ground5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ground5MouseEntered
        
    }//GEN-LAST:event_ground5MouseEntered

    private void ground6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ground6MouseEntered
        
    }//GEN-LAST:event_ground6MouseEntered

    private void ground5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ground5MouseExited
        
    }//GEN-LAST:event_ground5MouseExited

    private void ground6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ground6MouseExited
        
    }//GEN-LAST:event_ground6MouseExited

    private void CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorActionPerformed

    }//GEN-LAST:event_CalculatorActionPerformed

    private void CalculatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatorMouseEntered
        Calculator.setBackground(new Color (255,102,102));
        Calculator.setForeground(Color.black);
    }//GEN-LAST:event_CalculatorMouseEntered

    private void CalculatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatorMouseExited
        Calculator.setBackground(new Color (153,0,0));
        Calculator.setForeground(Color.white);
    }//GEN-LAST:event_CalculatorMouseExited

    private void Calculator1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Calculator1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculator1MouseEntered

    private void Calculator1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Calculator1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculator1MouseExited

    private void Calculator1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculator1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculator1ActionPerformed

    private void result_speedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_speedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_speedActionPerformed

    private void imput_value5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imput_value5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imput_value5ActionPerformed

    private void Calculator2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Calculator2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculator2MouseEntered

    private void Calculator2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Calculator2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculator2MouseExited

    private void Calculator2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculator2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculator2ActionPerformed

    private void imput_value5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imput_value5MouseClicked

    }//GEN-LAST:event_imput_value5MouseClicked

    private void imput_value5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imput_value5MousePressed
          imput_value5.setText("");
          imput_value5.setForeground(new Color (0, 0, 0));
    }//GEN-LAST:event_imput_value5MousePressed

    private void Calculator1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Calculator1MouseClicked
//DERIVADA DE LA POSICION: //
            int a = 2;
            int b = 3;
            int c = 1;
            int d = 2;
            int n = 4;
        Value_position.setText(a + "t^" + n + " - " + b + "t^" + (n - 1) + " + " + c + "t^" + (n - 2) + " + " + d);
        Value_position.getText();
//DERIVADA DE LA VELOCIDAD: //
            int e = a*n;
            int f = b*(n-1);
            int g = c*(n-2);
        Value_speed.setText(e + "t^" + (n-1) + " - " + f + "t^" + (n - 2) + " + " + g + "t^" + (n - 3));
        Value_speed.getText();
//DERIVADA DE LA ACELERACION: //
           int h = e*(n-1);
           int i = f*(n-2);
           int j = g*(n-3);
        Value_acceleration.setText(h + "t^" + (n-2) + " - " + i + "t^" + (n - 3) + " + " + j + "t^" + (n - 4));
        Value_acceleration.getText();
    }//GEN-LAST:event_Calculator1MouseClicked

    private void Calculator2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Calculator2MouseClicked
 //VARIABLES QUE DEFINIMOS EN LA DERIVADA//
            int a = 2;
            int b = 3;
            int c = 1;
            int d = 2;
            int n = 4;
            int e = a*n;
            int f = b*(n-1);
            int g = c*(n-2);
            int h = e*(n-1);
           int i = f*(n-2);
           int j = g*(n-3);
           
//MANDAMOS A LLAMAR AL TIEMPO QUE ESTABLECEMOS EN IMPUT_VALUE5 Y LO TRANSFORMAMOS A INT//
           String valort = imput_value5.getText();
           double t = Double.parseDouble(valort);
           
//ARÍMETICA ´POSICIÓN´A FUNIÓN DEL TIEMPO//
           double posicionT = a * Math.pow(t, n) - b * Math.pow(t, n - 1) + c * Math.pow(t, n - 2) + d;
           result_position.setText(String.valueOf(posicionT) + " m");
           
//ARÍMETICA´VELOCIDAD´ A FUNCIÓN DEL TIEMPO//
            double velocidadT = e * Math.pow(t, n - 1) - f * Math.pow(t, n - 2) + g * Math.pow(t, n - 3);
            result_speed.setText(String.valueOf(velocidadT) + " m/s");
            
//ARÍMERTICA´ACELERACIÓN´ A FUNCIÓN DEL TIEMPO//
           double acelaracionT = h * Math.pow(t, n - 2) - i * Math.pow(t, n - 3) + j * Math.pow(t, n - 4);
           result_aceleration.setText(String.valueOf(acelaracionT) + " m/s^2");
           
        
    }//GEN-LAST:event_Calculator2MouseClicked

    private void result_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_positionActionPerformed

    private void imput_value6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imput_value6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imput_value6ActionPerformed

    private void CalculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatorMouseClicked
            int a = 2;
            int b = 3;
            int c = 1;
            int n = 4;
            int e = a*n;
            int f = b*(n-1);
            int g = c*(n-2);
            int h = e*(n-1);
           int i = f*(n-2);
           int j = g*(n-3);
           
        String valort = imput_value5.getText();
           double t = Integer.parseInt(valort);
                double v0 = 0;
                
                double aceleracionT = h * Math.pow(t, n - 2) - i * Math.pow(t, n - 3) + j * Math.pow(t, n - 4);
        
        double distanciaF = v0 * t + 0.5 * aceleracionT* (t*t);
        imput_value6.setText(String.valueOf(distanciaF) + " m");
    }//GEN-LAST:event_CalculatorMouseClicked

    private void Value_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Value_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Value_positionActionPerformed

    private void Boton_de_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_de_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_de_inicioActionPerformed

    private void Boton_de_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_de_inicioMouseClicked
        Start_Window ve = new Start_Window();
        ve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_de_inicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CinematicaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CinematicaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CinematicaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CinematicaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CinematicaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_de_inicio;
    private javax.swing.JButton Calculator;
    private javax.swing.JButton Calculator1;
    private javax.swing.JButton Calculator2;
    private javax.swing.JLabel Derivada;
    private javax.swing.JPanel Ground_Derivada;
    private javax.swing.JPanel Ground_fun_time;
    private javax.swing.JLabel Position;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator_General5;
    private javax.swing.JLabel Speed;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Value5;
    private javax.swing.JLabel Value6;
    private javax.swing.JTextField Value_acceleration;
    private javax.swing.JTextField Value_position;
    private javax.swing.JTextField Value_speed;
    private javax.swing.JLabel acceleration;
    private javax.swing.JPanel background;
    private javax.swing.JPanel background_title;
    private javax.swing.JLabel fun_aceleration;
    private javax.swing.JLabel fun_position;
    private javax.swing.JLabel fun_speed;
    private javax.swing.JLabel fun_time_titile;
    private javax.swing.JPanel ground5;
    private javax.swing.JPanel ground6;
    private javax.swing.JTextField imput_value5;
    private javax.swing.JTextField imput_value6;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField result_aceleration;
    private javax.swing.JTextField result_position;
    private javax.swing.JTextField result_speed;
    // End of variables declaration//GEN-END:variables
}