/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinematicaparticula;

/**
 *
 * @author renzo
 */
public class MRU_Panel extends javax.swing.JFrame {

    /**
     * Creates new form MRU_Panel
     */
    public MRU_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background_title_MRU = new javax.swing.JPanel();
        Title_MRU = new javax.swing.JLabel();
        Distancia_Fondo = new javax.swing.JPanel();
        Distancia_Titulo = new javax.swing.JLabel();
        d_Velocidad2 = new javax.swing.JLabel();
        imput_v2 = new javax.swing.JTextField();
        t_Velocidad2 = new javax.swing.JLabel();
        imput_t2 = new javax.swing.JTextField();
        Velocidad_Fondo = new javax.swing.JPanel();
        Velocidad_Titulo = new javax.swing.JLabel();
        d_Velocidad = new javax.swing.JLabel();
        imput_d = new javax.swing.JTextField();
        t_Velocidad = new javax.swing.JLabel();
        imput_t = new javax.swing.JTextField();
        Tiempo_Fondo = new javax.swing.JPanel();
        Tiempo_Titulo = new javax.swing.JLabel();
        d_Velocidad1 = new javax.swing.JLabel();
        imput_d1 = new javax.swing.JTextField();
        t_Velocidad1 = new javax.swing.JLabel();
        imput_v1 = new javax.swing.JTextField();
        Boton_d = new javax.swing.JButton();
        Fondo_t = new javax.swing.JPanel();
        t_titulo = new javax.swing.JLabel();
        t_salida = new javax.swing.JTextField();
        Boton_t = new javax.swing.JButton();
        Fondo_Result_v = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        resultado_v = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        d_salida = new javax.swing.JTextField();
        Boton_v = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Boton_de_inicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background_title_MRU.setBackground(new java.awt.Color(255, 204, 204));
        background_title_MRU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        background_title_MRU.setForeground(new java.awt.Color(255, 255, 255));

        Title_MRU.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Title_MRU.setText("CÁLCULO CON MRU");

        javax.swing.GroupLayout background_title_MRULayout = new javax.swing.GroupLayout(background_title_MRU);
        background_title_MRU.setLayout(background_title_MRULayout);
        background_title_MRULayout.setHorizontalGroup(
            background_title_MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_title_MRULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_MRU)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background_title_MRULayout.setVerticalGroup(
            background_title_MRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_title_MRULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_MRU)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(background_title_MRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 60));

        Distancia_Fondo.setBackground(new java.awt.Color(204, 255, 255));
        Distancia_Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Distancia_Titulo.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        Distancia_Titulo.setForeground(new java.awt.Color(153, 204, 0));
        Distancia_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Distancia_Titulo.setText("DISTANCIA");

        d_Velocidad2.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        d_Velocidad2.setForeground(new java.awt.Color(0, 0, 153));
        d_Velocidad2.setText("VELOCIDAD: ");

        imput_v2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        t_Velocidad2.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        t_Velocidad2.setForeground(new java.awt.Color(102, 0, 102));
        t_Velocidad2.setText("TIEMPO: ");

        imput_t2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout Distancia_FondoLayout = new javax.swing.GroupLayout(Distancia_Fondo);
        Distancia_Fondo.setLayout(Distancia_FondoLayout);
        Distancia_FondoLayout.setHorizontalGroup(
            Distancia_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Distancia_Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Distancia_FondoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Distancia_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_Velocidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_Velocidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imput_v2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(imput_t2))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        Distancia_FondoLayout.setVerticalGroup(
            Distancia_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Distancia_FondoLayout.createSequentialGroup()
                .addComponent(Distancia_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d_Velocidad2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imput_v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_Velocidad2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imput_t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel1.add(Distancia_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 210, 180));

        Velocidad_Fondo.setBackground(new java.awt.Color(255, 255, 153));
        Velocidad_Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Velocidad_Titulo.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        Velocidad_Titulo.setForeground(new java.awt.Color(204, 102, 255));
        Velocidad_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Velocidad_Titulo.setText("VELOCIDAD");

        d_Velocidad.setBackground(new java.awt.Color(51, 255, 204));
        d_Velocidad.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        d_Velocidad.setForeground(new java.awt.Color(0, 102, 102));
        d_Velocidad.setText("DISTANCIA: ");

        imput_d.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        imput_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imput_dActionPerformed(evt);
            }
        });

        t_Velocidad.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        t_Velocidad.setForeground(new java.awt.Color(102, 0, 102));
        t_Velocidad.setText("TIEMPO: ");

        imput_t.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout Velocidad_FondoLayout = new javax.swing.GroupLayout(Velocidad_Fondo);
        Velocidad_Fondo.setLayout(Velocidad_FondoLayout);
        Velocidad_FondoLayout.setHorizontalGroup(
            Velocidad_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Velocidad_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addGroup(Velocidad_FondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Velocidad_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(d_Velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_Velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imput_t, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(imput_d))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Velocidad_FondoLayout.setVerticalGroup(
            Velocidad_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Velocidad_FondoLayout.createSequentialGroup()
                .addComponent(Velocidad_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d_Velocidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imput_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_Velocidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imput_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel1.add(Velocidad_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, 180));

        Tiempo_Fondo.setBackground(new java.awt.Color(204, 204, 255));
        Tiempo_Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Tiempo_Titulo.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        Tiempo_Titulo.setForeground(new java.awt.Color(0, 204, 0));
        Tiempo_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempo_Titulo.setText("TIEMPO");
        Tiempo_Titulo.setFocusable(false);
        Tiempo_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tiempo_Titulo.setVerifyInputWhenFocusTarget(false);

        d_Velocidad1.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        d_Velocidad1.setForeground(new java.awt.Color(0, 102, 102));
        d_Velocidad1.setText("DISTANCIA: ");

        imput_d1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        t_Velocidad1.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        t_Velocidad1.setForeground(new java.awt.Color(0, 51, 153));
        t_Velocidad1.setText("VELOCIDAD: ");

        imput_v1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout Tiempo_FondoLayout = new javax.swing.GroupLayout(Tiempo_Fondo);
        Tiempo_Fondo.setLayout(Tiempo_FondoLayout);
        Tiempo_FondoLayout.setHorizontalGroup(
            Tiempo_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tiempo_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addGroup(Tiempo_FondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Tiempo_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_Velocidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_Velocidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imput_d1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(imput_v1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Tiempo_FondoLayout.setVerticalGroup(
            Tiempo_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tiempo_FondoLayout.createSequentialGroup()
                .addComponent(Tiempo_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d_Velocidad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imput_d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_Velocidad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imput_v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel1.add(Tiempo_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 210, 180));

        Boton_d.setBackground(new java.awt.Color(0, 102, 102));
        Boton_d.setForeground(new java.awt.Color(204, 255, 255));
        Boton_d.setText("CALCULAR");
        Boton_d.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_dActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 130, 40));

        Fondo_t.setBackground(new java.awt.Color(204, 204, 255));
        Fondo_t.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        t_titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        t_titulo.setForeground(new java.awt.Color(0, 102, 0));
        t_titulo.setText("EL TIEMPO ES: ");

        t_salida.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout Fondo_tLayout = new javax.swing.GroupLayout(Fondo_t);
        Fondo_t.setLayout(Fondo_tLayout);
        Fondo_tLayout.setHorizontalGroup(
            Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_tLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Fondo_tLayout.setVerticalGroup(
            Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_tLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(t_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(Fondo_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 160, 90));

        Boton_t.setBackground(new java.awt.Color(102, 102, 0));
        Boton_t.setForeground(new java.awt.Color(255, 255, 204));
        Boton_t.setText("CALCULAR");
        Boton_t.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_tActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 130, 40));

        Fondo_Result_v.setBackground(new java.awt.Color(255, 255, 204));
        Fondo_Result_v.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 255));
        jLabel2.setText("LA VELOCIDAD ES: ");

        resultado_v.setEditable(false);
        resultado_v.setBackground(new java.awt.Color(255, 255, 255));
        resultado_v.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        resultado_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado_vActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo_Result_vLayout = new javax.swing.GroupLayout(Fondo_Result_v);
        Fondo_Result_v.setLayout(Fondo_Result_vLayout);
        Fondo_Result_vLayout.setHorizontalGroup(
            Fondo_Result_vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_Result_vLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Fondo_Result_vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultado_v, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        Fondo_Result_vLayout.setVerticalGroup(
            Fondo_Result_vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_Result_vLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultado_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(Fondo_Result_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 160, 90));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 0));
        jLabel3.setText("LA DISTANCIA ES: ");

        d_salida.setEditable(false);
        d_salida.setBackground(new java.awt.Color(255, 255, 255));
        d_salida.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        Boton_v.setBackground(new java.awt.Color(0, 0, 102));
        Boton_v.setForeground(new java.awt.Color(204, 204, 255));
        Boton_v.setText("CALCULAR");
        Boton_v.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_vActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 130, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinematicaparticula/Imagen/UA_logo_de_la_universidad_autónoma (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        Boton_de_inicio.setBackground(new java.awt.Color(204, 102, 0));
        Boton_de_inicio.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        Boton_de_inicio.setForeground(new java.awt.Color(255, 255, 0));
        Boton_de_inicio.setText("INICIO");
        Boton_de_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_de_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_de_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imput_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imput_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imput_dActionPerformed

    private void resultado_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado_vActionPerformed

    private void Boton_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_tActionPerformed
           String distanciaObt = imput_d.getText();
           double d = Integer.parseInt(distanciaObt);
           
           String tiempoObt = imput_t.getText();
           double t = Integer.parseInt(tiempoObt);
           
           double velocidad = d/t;
           resultado_v.setText(String.valueOf(velocidad) + " m/s");
    }//GEN-LAST:event_Boton_tActionPerformed

    private void Boton_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_vActionPerformed
        String distanciaObt = imput_d1.getText();
           double d = Integer.parseInt(distanciaObt);
           
           String velocidadObt = imput_v1.getText();
           double v = Integer.parseInt(velocidadObt);
           
           double tiempo = d/v;
           t_salida.setText(String.valueOf(tiempo) + " s");
    }//GEN-LAST:event_Boton_vActionPerformed

    private void Boton_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_dActionPerformed
        String velocidadObt = imput_v2.getText();
           double v = Integer.parseInt(velocidadObt);
           
           String tiempoObt = imput_t2.getText();
           double t = Integer.parseInt(tiempoObt);
           
           double distancia = v * t;
           d_salida.setText(String.valueOf(distancia) + " m");
    }//GEN-LAST:event_Boton_dActionPerformed

    private void Boton_de_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_de_inicioActionPerformed
        Start_Window ve = new Start_Window();
        ve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_de_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MRU_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MRU_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MRU_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MRU_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MRU_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_d;
    private javax.swing.JButton Boton_de_inicio;
    private javax.swing.JButton Boton_t;
    private javax.swing.JButton Boton_v;
    private javax.swing.JPanel Distancia_Fondo;
    private javax.swing.JLabel Distancia_Titulo;
    private javax.swing.JPanel Fondo_Result_v;
    private javax.swing.JPanel Fondo_t;
    private javax.swing.JPanel Tiempo_Fondo;
    private javax.swing.JLabel Tiempo_Titulo;
    private javax.swing.JLabel Title_MRU;
    private javax.swing.JPanel Velocidad_Fondo;
    private javax.swing.JLabel Velocidad_Titulo;
    private javax.swing.JPanel background_title_MRU;
    private javax.swing.JLabel d_Velocidad;
    private javax.swing.JLabel d_Velocidad1;
    private javax.swing.JLabel d_Velocidad2;
    private javax.swing.JTextField d_salida;
    private javax.swing.JTextField imput_d;
    private javax.swing.JTextField imput_d1;
    private javax.swing.JTextField imput_t;
    private javax.swing.JTextField imput_t2;
    private javax.swing.JTextField imput_v1;
    private javax.swing.JTextField imput_v2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField resultado_v;
    private javax.swing.JLabel t_Velocidad;
    private javax.swing.JLabel t_Velocidad1;
    private javax.swing.JLabel t_Velocidad2;
    private javax.swing.JTextField t_salida;
    private javax.swing.JLabel t_titulo;
    // End of variables declaration//GEN-END:variables
}
