/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinematicaparticula;

/**
 *
 * @author renzo
 */
public class MRUV_Panel extends javax.swing.JFrame {

    /**
     * Creates new form MRUV_Panel
     */
    public MRUV_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        background_title_MRUV = new javax.swing.JPanel();
        Title_MRV = new javax.swing.JLabel();
        Fondo_t = new javax.swing.JPanel();
        t_Titulo = new javax.swing.JLabel();
        Entrada_Vf_5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Entrada_v0_5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Entrada_a_5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Salida_t = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Calcular_t = new javax.swing.JButton();
        Fondo_v0 = new javax.swing.JPanel();
        v0_Titulo1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Entrada_Vf_1 = new javax.swing.JTextField();
        a_Titulo = new javax.swing.JLabel();
        Entrada_a_1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Entrada_t_1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Salida_v0 = new javax.swing.JTextField();
        Calulcar_v0 = new javax.swing.JButton();
        Fondo_v2 = new javax.swing.JPanel();
        v0_Titulo2 = new javax.swing.JLabel();
        Entrada_v0_2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Entrada_a_2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Entrada_t_2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Salida_Vf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Calular_Vf = new javax.swing.JButton();
        Fondo_v3 = new javax.swing.JPanel();
        v0_Titulo3 = new javax.swing.JLabel();
        Entrada_Vf_3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Entrada_v0_3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Entrada_t_3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Salida_a = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Calcular_a = new javax.swing.JButton();
        Fondo_v4 = new javax.swing.JPanel();
        v0_Titulo4 = new javax.swing.JLabel();
        Entrada_v0_4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Entrada_a_4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Entrada_t_4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        Salida_des = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Calcular_des = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Boton_de_inicio = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background_title_MRUV.setBackground(new java.awt.Color(255, 204, 204));
        background_title_MRUV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        background_title_MRUV.setForeground(new java.awt.Color(255, 255, 255));

        Title_MRV.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Title_MRV.setText("CÁLCULO DEL MRUV");

        javax.swing.GroupLayout background_title_MRUVLayout = new javax.swing.GroupLayout(background_title_MRUV);
        background_title_MRUV.setLayout(background_title_MRUVLayout);
        background_title_MRUVLayout.setHorizontalGroup(
            background_title_MRUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_title_MRUVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_MRV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background_title_MRUVLayout.setVerticalGroup(
            background_title_MRUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_title_MRUVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_MRV)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(background_title_MRUV, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 270, 60));

        Fondo_t.setBackground(new java.awt.Color(204, 255, 255));
        Fondo_t.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        t_Titulo.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        t_Titulo.setForeground(new java.awt.Color(0, 102, 102));
        t_Titulo.setText("TIEMPO");
        t_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Entrada_Vf_5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Entrada_Vf_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_Vf_5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("INGRESE VELOCIDAD FINAL:");

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("INGRESE VELOCIDAD INICIAL:");

        Entrada_v0_5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("INGRESE ACELERACION:");

        Entrada_a_5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Entrada_a_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_a_5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Salida_t.setEditable(false);
        Salida_t.setBackground(new java.awt.Color(255, 255, 255));
        Salida_t.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("\"t\" es:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(Salida_t, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salida_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Calcular_t.setBackground(new java.awt.Color(0, 153, 153));
        Calcular_t.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calcular_t.setForeground(new java.awt.Color(255, 255, 255));
        Calcular_t.setText("CALCULAR");
        Calcular_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular_tActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo_tLayout = new javax.swing.GroupLayout(Fondo_t);
        Fondo_t.setLayout(Fondo_tLayout);
        Fondo_tLayout.setHorizontalGroup(
            Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_tLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Calcular_t)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Fondo_tLayout.createSequentialGroup()
                .addGroup(Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_tLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Entrada_v0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_tLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(Fondo_tLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Entrada_Vf_5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_tLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(Fondo_tLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_tLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_tLayout.createSequentialGroup()
                        .addComponent(t_Titulo)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_tLayout.createSequentialGroup()
                        .addComponent(Entrada_a_5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        Fondo_tLayout.setVerticalGroup(
            Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_tLayout.createSequentialGroup()
                .addComponent(t_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_Vf_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_v0_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_a_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Fondo_tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_tLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(Fondo_tLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Calcular_t, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        jPanel1.add(Fondo_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, 240, 340));

        Fondo_v0.setBackground(new java.awt.Color(255, 204, 204));
        Fondo_v0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        v0_Titulo1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        v0_Titulo1.setForeground(new java.awt.Color(102, 0, 0));
        v0_Titulo1.setText("VELOCIDAD INICIAL");
        v0_Titulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("INGRESE VELOCIDAD FINAL:");

        Entrada_Vf_1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        a_Titulo.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        a_Titulo.setForeground(new java.awt.Color(0, 0, 153));
        a_Titulo.setText("INGRESE ACELERACION:");

        Entrada_a_1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 102, 0));
        jLabel7.setText("INGRESE TIEMPO:");

        Entrada_t_1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setForeground(new java.awt.Color(153, 0, 51));

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("\"v0\" es:");

        Salida_v0.setEditable(false);
        Salida_v0.setBackground(new java.awt.Color(255, 255, 255));
        Salida_v0.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(Salida_v0, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Salida_v0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Calulcar_v0.setBackground(new java.awt.Color(153, 51, 0));
        Calulcar_v0.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calulcar_v0.setForeground(new java.awt.Color(255, 255, 255));
        Calulcar_v0.setText("CALCULAR");
        Calulcar_v0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calulcar_v0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calulcar_v0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo_v0Layout = new javax.swing.GroupLayout(Fondo_v0);
        Fondo_v0.setLayout(Fondo_v0Layout);
        Fondo_v0Layout.setHorizontalGroup(
            Fondo_v0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_v0Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Calulcar_v0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Fondo_v0Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Fondo_v0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Entrada_a_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entrada_t_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Fondo_v0Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(v0_Titulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Fondo_v0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fondo_v0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(a_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Fondo_v0Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Entrada_Vf_1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Fondo_v0Layout.setVerticalGroup(
            Fondo_v0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_v0Layout.createSequentialGroup()
                .addComponent(v0_Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_Vf_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_a_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_t_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Fondo_v0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_v0Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v0Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Calulcar_v0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(Fondo_v0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 340));

        Fondo_v2.setBackground(new java.awt.Color(204, 204, 255));
        Fondo_v2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        v0_Titulo2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        v0_Titulo2.setForeground(new java.awt.Color(0, 0, 102));
        v0_Titulo2.setText("VELOCIIDAD FINAL");
        v0_Titulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Entrada_v0_2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 204));
        jLabel9.setText("INGRESE VELOCIDAD INICIAL:");

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("INGRESE ACELERACION:");

        Entrada_a_2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 102, 0));
        jLabel11.setText("INGRESE TIEMPO:");

        Entrada_t_2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Salida_Vf.setEditable(false);
        Salida_Vf.setBackground(new java.awt.Color(255, 255, 255));
        Salida_Vf.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Salida_Vf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salida_VfActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("\"Vf\" es:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salida_Vf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Salida_Vf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Calular_Vf.setBackground(new java.awt.Color(0, 102, 153));
        Calular_Vf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calular_Vf.setForeground(new java.awt.Color(255, 255, 255));
        Calular_Vf.setText("CALCULAR");
        Calular_Vf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calular_Vf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calular_VfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo_v2Layout = new javax.swing.GroupLayout(Fondo_v2);
        Fondo_v2.setLayout(Fondo_v2Layout);
        Fondo_v2Layout.setHorizontalGroup(
            Fondo_v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_v2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Calular_Vf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Fondo_v2Layout.createSequentialGroup()
                .addGroup(Fondo_v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Entrada_v0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(Fondo_v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Entrada_t_2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Entrada_a_2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(v0_Titulo2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Fondo_v2Layout.setVerticalGroup(
            Fondo_v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_v2Layout.createSequentialGroup()
                .addComponent(v0_Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_v0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_a_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(Entrada_t_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Fondo_v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Calular_Vf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(Fondo_v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 240, 340));

        Fondo_v3.setBackground(new java.awt.Color(255, 255, 204));
        Fondo_v3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        v0_Titulo3.setBackground(new java.awt.Color(153, 153, 0));
        v0_Titulo3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        v0_Titulo3.setForeground(new java.awt.Color(102, 102, 0));
        v0_Titulo3.setText("ACELERACIÓN");
        v0_Titulo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Entrada_Vf_3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Entrada_Vf_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_Vf_3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("INGRESE VELOCIDAD FINAL:");

        jLabel14.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 204));
        jLabel14.setText("INGRESE VELOCIDAD INICIAL:");

        Entrada_v0_3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 102, 0));
        jLabel15.setText("INGRESE TIEMPO:");

        Entrada_t_3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(102, 102, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Salida_a.setEditable(false);
        Salida_a.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("\"a\" es:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salida_a, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salida_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Calcular_a.setBackground(new java.awt.Color(153, 153, 0));
        Calcular_a.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calcular_a.setForeground(new java.awt.Color(255, 255, 255));
        Calcular_a.setText("CALCULAR");
        Calcular_a.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calcular_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo_v3Layout = new javax.swing.GroupLayout(Fondo_v3);
        Fondo_v3.setLayout(Fondo_v3Layout);
        Fondo_v3Layout.setHorizontalGroup(
            Fondo_v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_v3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Calcular_a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Fondo_v3Layout.createSequentialGroup()
                .addGroup(Fondo_v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Entrada_Vf_3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(v0_Titulo3))
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Entrada_v0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Fondo_v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Entrada_t_3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Fondo_v3Layout.setVerticalGroup(
            Fondo_v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_v3Layout.createSequentialGroup()
                .addComponent(v0_Titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_Vf_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_v0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_t_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Fondo_v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(Fondo_v3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Calcular_a, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        jPanel1.add(Fondo_v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 240, 340));

        Fondo_v4.setBackground(new java.awt.Color(204, 255, 204));
        Fondo_v4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        v0_Titulo4.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        v0_Titulo4.setForeground(new java.awt.Color(0, 153, 0));
        v0_Titulo4.setText("DESPLAZAMIENTO");
        v0_Titulo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Entrada_v0_4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 204));
        jLabel17.setText("INGRESE VELOCIDAD INICIAL:");

        jLabel18.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("INGRESE ACELERACION:");

        Entrada_a_4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 102, 0));
        jLabel19.setText("INGRESE TIEMPO:");

        Entrada_t_4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 153, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Salida_des.setEditable(false);
        Salida_des.setBackground(new java.awt.Color(255, 255, 255));
        Salida_des.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("\"x(t)\" es:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salida_des, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salida_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        Calcular_des.setBackground(new java.awt.Color(51, 153, 0));
        Calcular_des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calcular_des.setForeground(new java.awt.Color(255, 255, 255));
        Calcular_des.setText("CALCULAR");
        Calcular_des.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calcular_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular_desActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo_v4Layout = new javax.swing.GroupLayout(Fondo_v4);
        Fondo_v4.setLayout(Fondo_v4Layout);
        Fondo_v4Layout.setHorizontalGroup(
            Fondo_v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_v4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Calcular_des)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Fondo_v4Layout.createSequentialGroup()
                .addGroup(Fondo_v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_v4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Entrada_a_4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(Fondo_v4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Entrada_v0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo_v4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_v4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Fondo_v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_v4Layout.createSequentialGroup()
                        .addComponent(v0_Titulo4)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_v4Layout.createSequentialGroup()
                        .addComponent(Entrada_t_4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        Fondo_v4Layout.setVerticalGroup(
            Fondo_v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_v4Layout.createSequentialGroup()
                .addComponent(v0_Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_v0_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_a_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_t_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Fondo_v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_v4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Calcular_des, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(Fondo_v4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        jPanel1.add(Fondo_v4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 240, 340));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinematicaparticula/Imagen/UA_logo_de_la_universidad_autónoma (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, -1, -1));

        Boton_de_inicio.setBackground(new java.awt.Color(204, 102, 0));
        Boton_de_inicio.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        Boton_de_inicio.setForeground(new java.awt.Color(255, 255, 0));
        Boton_de_inicio.setText("INICIO");
        Boton_de_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_de_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_de_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Entrada_Vf_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_Vf_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_Vf_5ActionPerformed

    private void Calulcar_v0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calulcar_v0ActionPerformed
        String velocidadF = Entrada_Vf_1.getText();
        double vf = Integer.parseInt(velocidadF);
        
        String aceleracion = Entrada_a_1.getText();
        double a = Integer.parseInt(aceleracion);
        
        String tiempo = Entrada_t_1.getText();
        double t = Integer.parseInt(tiempo);
        
        double v0 = vf - (a * t);
        Salida_v0.setText(String.valueOf(v0) + " m/s");
    }//GEN-LAST:event_Calulcar_v0ActionPerformed

    private void Calular_VfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calular_VfActionPerformed
        String velocidadI2 = Entrada_v0_2.getText();
        double v0 = Integer.parseInt(velocidadI2);
        
        String aceleracion2 = Entrada_a_2.getText();
        double a = Integer.parseInt(aceleracion2);
        
        String tiempo2 = Entrada_t_2.getText();
        double t = Integer.parseInt(tiempo2);
        
        double vf = v0+ (a * t);
        Salida_Vf.setText(String.valueOf(vf) + " m/s");
    }//GEN-LAST:event_Calular_VfActionPerformed

    private void Entrada_a_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_a_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_a_5ActionPerformed

    private void Salida_VfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salida_VfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salida_VfActionPerformed

    private void Entrada_Vf_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_Vf_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_Vf_3ActionPerformed

    private void Calcular_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular_aActionPerformed
        String velocidadF3 = Entrada_Vf_3.getText();
        double Vf = Integer.parseInt(velocidadF3);
        
        String velocidadI3 = Entrada_v0_3.getText();
        double v0 = Integer.parseInt(velocidadI3);
        
        String tiempo3 = Entrada_t_3.getText();
        double t = Integer.parseInt(tiempo3);
        
        double a = (Vf - v0) / t;
        Salida_a.setText(String.valueOf(a) + " m/s^2");
    }//GEN-LAST:event_Calcular_aActionPerformed

    private void Calcular_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular_desActionPerformed
        String velocidadI4 = Entrada_v0_4.getText();
        double v0 = Integer.parseInt(velocidadI4);
        
        String aceleracion4 = Entrada_a_4.getText();
        double a = Integer.parseInt(aceleracion4);
        
        String tiempo4 = Entrada_t_4.getText();
        double t = Integer.parseInt(tiempo4);
        
        double des = v0 * t + 0.5 * a * (t*t);
        Salida_des.setText(String.valueOf(des) + " m");
    }//GEN-LAST:event_Calcular_desActionPerformed

    private void Calcular_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular_tActionPerformed
        String velocidadF5 = Entrada_Vf_5.getText();
        double Vf = Integer.parseInt(velocidadF5);
        
        String velocidadI5 = Entrada_v0_5.getText();
        double v0 = Integer.parseInt(velocidadI5);
        
        String aceleracion5 = Entrada_a_5.getText();
        double a = Integer.parseInt(aceleracion5);
        
        double t = (Vf - v0) / a;
        Salida_t.setText(String.valueOf(t) + " min");
    }//GEN-LAST:event_Calcular_tActionPerformed

    private void Boton_de_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_de_inicioActionPerformed
        Start_Window ve = new Start_Window();
        ve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_de_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MRUV_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MRUV_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MRUV_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MRUV_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MRUV_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_de_inicio;
    private javax.swing.JButton Calcular_a;
    private javax.swing.JButton Calcular_des;
    private javax.swing.JButton Calcular_t;
    private javax.swing.JButton Calular_Vf;
    private javax.swing.JButton Calulcar_v0;
    private javax.swing.JTextField Entrada_Vf_1;
    private javax.swing.JTextField Entrada_Vf_3;
    private javax.swing.JTextField Entrada_Vf_5;
    private javax.swing.JTextField Entrada_a_1;
    private javax.swing.JTextField Entrada_a_2;
    private javax.swing.JTextField Entrada_a_4;
    private javax.swing.JTextField Entrada_a_5;
    private javax.swing.JTextField Entrada_t_1;
    private javax.swing.JTextField Entrada_t_2;
    private javax.swing.JTextField Entrada_t_3;
    private javax.swing.JTextField Entrada_t_4;
    private javax.swing.JTextField Entrada_v0_2;
    private javax.swing.JTextField Entrada_v0_3;
    private javax.swing.JTextField Entrada_v0_4;
    private javax.swing.JTextField Entrada_v0_5;
    private javax.swing.JPanel Fondo_t;
    private javax.swing.JPanel Fondo_v0;
    private javax.swing.JPanel Fondo_v2;
    private javax.swing.JPanel Fondo_v3;
    private javax.swing.JPanel Fondo_v4;
    private javax.swing.JTextField Salida_Vf;
    private javax.swing.JTextField Salida_a;
    private javax.swing.JTextField Salida_des;
    private javax.swing.JTextField Salida_t;
    private javax.swing.JTextField Salida_v0;
    private javax.swing.JLabel Title_MRV;
    private javax.swing.JLabel a_Titulo;
    private javax.swing.JPanel background_title_MRUV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel t_Titulo;
    private javax.swing.JLabel v0_Titulo1;
    private javax.swing.JLabel v0_Titulo2;
    private javax.swing.JLabel v0_Titulo3;
    private javax.swing.JLabel v0_Titulo4;
    // End of variables declaration//GEN-END:variables
}
