/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinematicaparticula;

/**
 *
 * @author renzo
 */
public class Start_Window extends javax.swing.JFrame {

    /**
     * Creates new form Start_Window
     */
    public Start_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Fondo_de_opciones = new javax.swing.JPanel();
        MRU_opcion = new javax.swing.JButton();
        MRUV_opcion = new javax.swing.JButton();
        Derivada_opcion = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        Background.setBackground(new java.awt.Color(255, 153, 51));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Titulo.setText("BIENVENIDO");
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Titulo.setVerifyInputWhenFocusTarget(false);
        Background.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, 40));

        Fondo_de_opciones.setBackground(new java.awt.Color(255, 255, 255));

        MRU_opcion.setBackground(new java.awt.Color(255, 255, 204));
        MRU_opcion.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        MRU_opcion.setForeground(new java.awt.Color(204, 0, 0));
        MRU_opcion.setText("MRU");
        MRU_opcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MRU_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRU_opcionActionPerformed(evt);
            }
        });

        MRUV_opcion.setBackground(new java.awt.Color(255, 204, 153));
        MRUV_opcion.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        MRUV_opcion.setForeground(new java.awt.Color(204, 0, 0));
        MRUV_opcion.setText("MRUV");
        MRUV_opcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MRUV_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRUV_opcionActionPerformed(evt);
            }
        });

        Derivada_opcion.setBackground(new java.awt.Color(204, 204, 204));
        Derivada_opcion.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        Derivada_opcion.setForeground(new java.awt.Color(204, 0, 0));
        Derivada_opcion.setText("DERIVADAS");
        Derivada_opcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Derivada_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Derivada_opcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo_de_opcionesLayout = new javax.swing.GroupLayout(Fondo_de_opciones);
        Fondo_de_opciones.setLayout(Fondo_de_opcionesLayout);
        Fondo_de_opcionesLayout.setHorizontalGroup(
            Fondo_de_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_de_opcionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Fondo_de_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MRU_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MRUV_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Derivada_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Fondo_de_opcionesLayout.setVerticalGroup(
            Fondo_de_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_de_opcionesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MRU_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(MRUV_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Derivada_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        Background.add(Fondo_de_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 230, 330));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinematicaparticula/Imagen/UA_logo_de_la_universidad_autónoma (1) (1).png"))); // NOI18N
        Background.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Derivada_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Derivada_opcionActionPerformed
        CinematicaP ve = new CinematicaP();
        ve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Derivada_opcionActionPerformed

    private void MRUV_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRUV_opcionActionPerformed
        MRUV_Panel ve = new MRUV_Panel();
       ve.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_MRUV_opcionActionPerformed

    private void MRU_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRU_opcionActionPerformed
       MRU_Panel ve = new MRU_Panel();
        ve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MRU_opcionActionPerformed
//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Derivada_opcion;
    private javax.swing.JPanel Fondo_de_opciones;
    private javax.swing.JButton MRUV_opcion;
    private javax.swing.JButton MRU_opcion;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel22;
    // End of variables declaration//GEN-END:variables
}
